version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dalamud-sdk:
        patterns:
          - "Dalamud.NET.Sdk"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
